---
- hosts: all
  gather_facts: no
  remote_user: root
  roles:
    - role: "bootstrap"
      tags:
        - bootstrap
    - role: "prepare"
      tags:
        - prepare
    - role: "accounts"
      vars:
        default_groups:
          - wheel
        nopasswd_sudo: True
        users:
          - name: 'ansible'
            groups: ['wheel']
            append: True
            ssh_public_key: "~/.ssh/id_rsa.pub"
      tags:
        - users
        - accounts
    - role: "sshd"
      vars:
        sshd_Port: "22"
        sshd_ListenAddress: "0.0.0.0"
      tags:
        - sshd

