---
- name: Basic server hardening for cloud servers
  hosts: '{{ host | default("all") }}'
  gather_facts: no
  remote_user: root

  roles:
    - role: bootstrap
    - role: users
      vars:
        - ssh_user: random1
        - ssh_public_key: "~/.ssh/id_rsa.pub"
    - role: sshd
      vars:
        - sshd_port: 22

