---
- name: use specified port
  lineinfile:
    destfile: /etc/ssh/sshd_config
    regexp: '^Port'
    line: 'Port {{sshd_port}}'
    state: present
    insertafter: '^#Port'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd

- name: disable sshd root login
  lineinfile:
    destfile: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
    insertafter: '^#PermitRootLogin'
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
  - restart sshd

- name: run inventory
  setup:
